# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml
    - id: check-added-large-files
    - id: no-commit-to-branch
      args: [--branch, main, --branch, integration]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
    - id: terraform_validate
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_tflint
    - id: terraform_tfsec
- repo: https://github.com/devoteamgcloud/pre-commit-dataform
  rev: v1.0.2
  hooks:
    - id: dataform_format
